version: '3'
services:
  flet-app:
    container_name: flet-app
    ports:
      - "8888:8888"
    build:
      context: .
      dockerfile: main.Dockerfile
    volumes:
      - .:/app
    command: >-
      python main.py